// Prepares the kit photos in /mockups for the mockup (API and website):
// - "<kit>-blank.webp": the reference sheet blanked, i.e. the drawing printed on it erased by a median filter,
//   which keeps the paper's shading and the canvas' shadow;
// - "<kit>-overlay.png": what lies on top of the sheet (brushes, callout arcs and their lettering), transparent elsewhere;
// - "<kit>.js": both as data URLs for the website. An <img> from disk would block the canvas export when the page is
//   opened as a file, a script doesn't.
// Run it after replacing a kit photo or changing its geometry in src/core/mockup.ts: npm run prepare:mockups
const path = require("path");
const sharp = require("sharp");
const fs = require("fs");
const { MOCKUP_KITS_GLOBAL, MOCKUP_TEMPLATES } = require("../dist/src/core/mockup");

const dir = path.join(__dirname, "../../mockups");
/** Median filter size: wide enough to erase the sheet's lines and digits */
const CLEANUP = 15;

function insidePolygon(x, y, points) {
    let inside = false;
    for (let i = 0, j = points.length - 1; i < points.length; j = i++) {
        const [xi, yi] = points[i];
        const [xj, yj] = points[j];
        if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) {
            inside = !inside;
        }
    }
    return inside;
}

async function prepare(template) {
    const source = path.join(dir, template.source);
    const { width, height } = await sharp(source).metadata();
    const polygon = template.sheet.map((p) => p.join(",")).join(" ");

    // blank sheet: median-filtered pixels inside the sheet, the canvas put back on top
    const mask = Buffer.from(`<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}"><polygon points="${polygon}" fill="#fff"/></svg>`);
    const cleanedSheet = await sharp(source).median(CLEANUP).ensureAlpha().composite([{ input: mask, blend: "dest-in" }]).png().toBuffer();
    const canvasPatch = await sharp(source).extract(template.canvas).png().toBuffer();
    await sharp(source)
        .composite([{ input: cleanedSheet }, { input: canvasPatch, left: template.canvas.left, top: template.canvas.top }])
        .webp({ quality: 95 })
        .toFile(path.join(dir, template.blank));

    // overlay: saturated or dark pixels inside the sheet (the sheet itself is white paper with light grey lines)
    const { data, info } = await sharp(source).removeAlpha().raw().toBuffer({ resolveWithObject: true });
    const out = Buffer.alloc(info.width * info.height * 4);
    const xs = template.sheet.map((p) => p[0]);
    const ys = template.sheet.map((p) => p[1]);
    let kept = 0;
    for (let y = Math.max(0, Math.floor(Math.min(...ys))); y < Math.min(info.height, Math.ceil(Math.max(...ys))); y++) {
        for (let x = Math.max(0, Math.floor(Math.min(...xs))); x < Math.min(info.width, Math.ceil(Math.max(...xs))); x++) {
            const i = (y * info.width + x) * 3;
            const [r, g, b] = [data[i], data[i + 1], data[i + 2]];
            const saturation = Math.max(r, g, b) - Math.min(r, g, b);
            const luminance = 0.299 * r + 0.587 * g + 0.114 * b;
            if ((saturation > 28 || luminance < 110) && insidePolygon(x + 0.5, y + 0.5, template.sheet)) {
                const o = (y * info.width + x) * 4;
                out[o] = r;
                out[o + 1] = g;
                out[o + 2] = b;
                out[o + 3] = 255;
                kept++;
            }
        }
    }
    await sharp(out, { raw: { width: info.width, height: info.height, channels: 4 } })
        .png({ compressionLevel: 9 })
        .toFile(path.join(dir, template.overlay));
    const dataUrl = (file, type) => `data:${type};base64,${fs.readFileSync(path.join(dir, file)).toString("base64")}`;
    const layers = { blank: dataUrl(template.blank, "image/webp"), overlay: dataUrl(template.overlay, "image/png") };
    fs.writeFileSync(path.join(dir, template.script), `// Generated by server/scripts/prepare-mockups.js
`
        + `(window.${MOCKUP_KITS_GLOBAL} = window.${MOCKUP_KITS_GLOBAL} || {})[${JSON.stringify(template.name)}] = ${JSON.stringify(layers)};
`);
    console.log(`${template.name}: ${template.blank}, ${template.overlay}, ${template.script} (${kept} overlay pixels)`);
}

(async () => {
    for (const template of Object.values(MOCKUP_TEMPLATES)) {
        await prepare(template);
    }
})().catch((e) => {
    console.error(e);
    process.exit(1);
});
